#??
spring:
  profiles:
    default: local


---

spring:
  profiles:
    active: local
  kafka:
    producer:
      bootstrap-servers: 172.30.1.77:9092, 172.30.1.77:9093, 172.30.1.77:9094
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer