spring:
  cloud:
    config:
      name: car-service-common
  config:
    import: optional:configserver:http://127.0.0.1:8888/
  profiles:
    active: local
  application:
    name: bsm-service
server:
  port: 0

eureka:
  instance:
    instance-id: ${spring.cloud.client.ip-address}:${spring.application.instance_id:${random.value}}
  client:
    register-with-eureka: true
    fetch-registry: true

management:
  endpoints:
    web:
      exposure:
        include: health, refresh, metrics, env, info

logging:
  level:
    org.springframework.data.mongodb.core.MongoTemplate: DEBUG